[project]
name = "call-me-maybe-1337"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.13.4",
    "numpy>=2.2.6",
    "typing-extensions>=4.15.0",
    "flake8>=7.3.0",
    "mypy>=1.17.0",
    "rich>=15.0.0",
    "black>=26.5.1",
]

[tool.mypy]
python_version = "3.12"
mypy_path = "llm_sdk" 
explicit_package_bases = true
namespace_packages = true

[tool.uv.workspace]
members = ["llm_sdk"]
