"""Pydantic models for generated function-call payloads."""

from pydantic import BaseModel, RootModel, StringConstraints
from typing import TypeAlias, Annotated

Argument: TypeAlias = dict[str, str | float | bool | int]


class FunctionCallModel(BaseModel):
    """Represents one generated function call with its resolved parameters.

    Encapsulates a completed function call generated by the pipeline,
    including the function name, the prompt that generated it, and the
    resolved parameter values.

    Attributes:
        name: Name of the function to call (non-empty).
        prompt: The user prompt that generated this call (non-empty).
        parameters: Mapping of parameter names to their values.
    """
    name: Annotated[str, StringConstraints(min_length=1, strip_whitespace=True)]
    prompt: Annotated[str, StringConstraints(min_length=1, strip_whitespace=True)]
    parameters: Argument


class FunctionCallRootModel(RootModel[list[FunctionCallModel]]):
    """Root model for parsing a list of function calls from JSON.

    Wraps a list of FunctionCallModel objects for convenient JSON parsing
    and validation via Pydantic.
    """
    pass
